require "omniauth-picowork/version"
require "omniauth/strategies/dev"
require "omniauth/strategies/support"
require "omniauth/strategies/developer"
require "omniauth/strategies/tl_dev"
require "omniauth/strategies/tl_ctrip"
require "omniauth/strategies/alpha_prv"
require "omniauth/strategies/cn_alpha"